spring:
  profiles:
    active: dev

xyz:
  yuanwl:
    databaseplatform: mysql

    str: str
    b: true
    f: 99.9
    i: 999
    t: 21:01:01
    d: 2018-09-08
    n: null


    value: ${random.value}
    number: ${random.int}
    bignumber: ${random.long}
    test2: ${random.int[10,20]}
    test1: ${random.int(10)}

    list:
      - 0
      - 1
      - 2

    map:
      k0: 0
      k1: 1
      k2: 2

    refstr: ${xyz.yuanwl.str}
    reflist: ${xyz.yuanwl.list}
    refmap: ${xyz.yuanwl.map}
