spring:
  datasource:
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?characterEncoding=utf-8&useSSL=false
  jpa:
    open-in-view: true